[selection]
save_to_clipboard = true

[mouse]
bindings = [
  { mouse = "Right", mods = "None", action = "Copy" }
]

[terminal.shell]
program = "wsl.exe"
args = ["~"]

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }

[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
